POST http://127.0.0.1:3000/users

{
"name": "AlissoTeste",
"username": "grimmjow",
"email": "alissonsilvamorimduarte@gmail.com",
"phone": "84996304813",
"passwd": "teste1239",
"confirm_password":	"teste1239",
"birth_date": "2024-04-12",
"gender": "female"
}


GET http://127.0.0.1:3000/user/23

POST http://127.0.0.1:3000/users

{
"name":"alisson",
"cep":"5967030",
"birth_date":"1995-10-10",
"email":"alis1soan@gmail.com",
"passwd":"010111231212312",
"phone":"84999099999"
}



DELETE http://127.0.0.1:3000/user/16





